#!/usr/bin/env python3
"""
graph_oracle_feedback.py
========================
Graph-path-augmented Oracle (Human Proxy) feedback generator.

For structural errors (wrong join path), appends the correct FK traversal
path to the standard proxy feedback so the AI Agent has an explicit graph
road-map for its next attempt.

  Standard feedback:  "You joined the wrong tables ..."
  Augmented feedback: "You joined the wrong tables ...
                       The schema graph shows the required path is:
                       CAR_MAKERS -[Id=Maker]-> MODEL_LIST -[Model=Model]->
                       CAR_NAMES -[MakeId=Id]-> CARS_DATA"

Only the path string is added; the proxy wording is kept unchanged so we
can isolate the graph contribution in the ablation study.

Usage (programmatic)
--------------------
import sys; sys.path.insert(0, "StructGPT-Ollama")
from schema_graph import SchemaGraph
from graph_hitl_framework.grl_error_classifier import GRLErrorClassifier
from graph_hitl_framework.graph_oracle_feedback import GraphOracleFeedback

sg  = SchemaGraph("StructGPT-Ollama/data/spider/spider_data/tables.json")
clf = GRLErrorClassifier(sg)
gof = GraphOracleFeedback(sg, clf)

feedback = gof.generate(
    ai_message   = "I ran your SQL and got: [] ...",
    proxy_text   = "You joined the wrong tables. Try car_makers instead.",
    pred_sql     = "SELECT ... FROM car_names JOIN cars_data ...",
    gold_sql     = "SELECT ... FROM car_makers JOIN model_list ...",
    db_id        = "car_1",
    use_graph    = True,   # False → returns proxy_text unchanged
)
"""

import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "StructGPT-Ollama"))
sys.path.insert(0, str(ROOT / "graph_hitl_framework"))
from schema_graph import SchemaGraph, extract_tables_from_sql

from grl_error_classifier import GRLErrorClassifier


# ─── Template ─────────────────────────────────────────────────────────────────

_GRAPH_PATH_SUFFIX = (
    "\n\nThe schema graph shows the required foreign-key traversal path is:\n"
    "  {fk_path}\n"
    "Use this exact join sequence to reach the correct tables."
)

_MISSING_TABLE_SUFFIX = (
    "\n\nNote: your query is missing the following table(s) that are required "
    "to answer the question: {missing}. "
    "Check the foreign-key relationships to include them correctly."
)


# ─── GraphOracleFeedback ──────────────────────────────────────────────────────

class GraphOracleFeedback:
    """
    Wraps the standard Human Proxy feedback with optional FK-path injection.

    Parameters
    ----------
    schema_graph   : loaded SchemaGraph instance
    error_clf      : GRLErrorClassifier instance (reuses same SchemaGraph)
    """

    def __init__(self, schema_graph: SchemaGraph,
                 error_clf: GRLErrorClassifier):
        self.sg  = schema_graph
        self.clf = error_clf

    def generate(
        self,
        proxy_text: str,
        pred_sql:   str,
        gold_sql:   str,
        db_id:      str,
        use_graph:  bool = True,
    ) -> str:
        """
        Return augmented feedback string.

        Parameters
        ----------
        proxy_text  : feedback already generated by the Human Proxy LLM
        pred_sql    : SQL predicted by the AI Agent (failed)
        gold_sql    : gold SQL from the answer key
        db_id       : Spider database identifier
        use_graph   : if False, return proxy_text unchanged (ablation switch)

        Returns
        -------
        str — original proxy_text with optional graph path appended
        """
        if not use_graph:
            return proxy_text

        classification = self.clf.classify(pred_sql, gold_sql, db_id)
        error_type     = classification["error_type"]

        if error_type == "structural":
            fk_path = classification.get("fk_path")
            if fk_path:
                return proxy_text + _GRAPH_PATH_SUFFIX.format(fk_path=fk_path)
            # fk_path is None when SchemaGraph can't find the chain — fall back
            # to listing missing tables instead
            missing = classification.get("missing_tables", [])
            if missing:
                return proxy_text + _MISSING_TABLE_SUFFIX.format(
                    missing=", ".join(t.upper() for t in missing)
                )

        # surface error or unknown — plain proxy feedback is sufficient
        return proxy_text

    def classify_and_generate(
        self,
        proxy_text: str,
        pred_sql:   str,
        gold_sql:   str,
        db_id:      str,
        use_graph:  bool = True,
    ) -> tuple[str, dict]:
        """
        Same as generate() but also returns the classification dict.
        Useful for logging in the pipeline.
        """
        classification = self.clf.classify(pred_sql, gold_sql, db_id)
        error_type     = classification["error_type"]

        if not use_graph or error_type != "structural":
            return proxy_text, classification

        fk_path = classification.get("fk_path")
        if fk_path:
            return (proxy_text + _GRAPH_PATH_SUFFIX.format(fk_path=fk_path),
                    classification)

        missing = classification.get("missing_tables", [])
        if missing:
            return (proxy_text + _MISSING_TABLE_SUFFIX.format(
                        missing=", ".join(t.upper() for t in missing)),
                    classification)

        return proxy_text, classification


# ─── Smoke Test ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    tables_path = ROOT / "StructGPT-Ollama/data/spider/spider_data/tables.json"
    if not tables_path.exists():
        print(f"tables.json not found at {tables_path}")
        raise SystemExit(1)

    sg  = SchemaGraph(str(tables_path))
    clf = GRLErrorClassifier(sg)
    gof = GraphOracleFeedback(sg, clf)

    # ── Structural error ──────────────────────────────────────────────────────
    pred_structural = (
        "SELECT AVG(cars_data.mpg) FROM car_names "
        "JOIN cars_data ON car_names.makeid = cars_data.id "
        "WHERE car_names.make = 'usa'"
    )
    gold_structural = (
        "SELECT AVG(T4.mpg) FROM car_makers AS T1 "
        "JOIN model_list AS T2 ON T1.id = T2.maker "
        "JOIN car_names  AS T3 ON T2.model = T3.model "
        "JOIN cars_data  AS T4 ON T3.makeid = T4.id "
        "WHERE T1.country = 'usa'"
    )
    proxy_text = "You joined the wrong tables — the country is on car_makers, not car_names."

    augmented, clf_result = gof.classify_and_generate(
        proxy_text=proxy_text,
        pred_sql=pred_structural,
        gold_sql=gold_structural,
        db_id="car_1",
        use_graph=True,
    )
    print("\n── Structural error test (car_1) ──")
    print(f"  error_type     : {clf_result['error_type']}")
    print(f"  missing_tables : {clf_result['missing_tables']}")
    print(f"  fk_path        : {clf_result['fk_path']}")
    print(f"\nAugmented feedback:\n{augmented}")

    # ── Surface error (same tables, wrong function) ───────────────────────────
    pred_surface = "SELECT COUNT(*) FROM singer WHERE age > 25"
    gold_surface = "SELECT AVG(age) FROM singer WHERE age > 25"
    proxy_text2  = "The function is wrong — you need AVG, not COUNT."

    aug2, clf2 = gof.classify_and_generate(
        proxy_text=proxy_text2,
        pred_sql=pred_surface,
        gold_sql=gold_surface,
        db_id="concert_singer",
        use_graph=True,
    )
    print("\n── Surface error test (concert_singer) ──")
    print(f"  error_type : {clf2['error_type']}")
    print(f"\nFeedback (should be unchanged):\n{aug2}")
    print(f"\n  Unchanged: {aug2 == proxy_text2}")
